### ISSUE TITLE
Optionally render output with LaTeX

### ISSUE THREAD

**Issue by jonpalmisc** [jonpalmisc/Maui#2]
Output is currently limited to plain text. Being able to receive output as LaTeX and render it would provide far greater graphical fidelity.

**Comment by xusheng6** [comment]
You can do it with `Export["~/a.tex", %]`, which exports the last result in tex form.

Surprisingly, the [TexForm](https://reference.wolfram.com/language/ref/TeXForm.html) function does not work:

<img width="586" alt="Screen Shot 2022-03-27 at 3 45 48 PM" src="https://user-images.githubusercontent.com/94503187/160272007-9ab262d4-8818-4101-8a98-30235203e128.png">

**Comment by xusheng6** [comment]
Now `TeXForm` works with this fix: f8cd55afad550ba70b3e801ead949a9f4100b9ae
