### ISSUE TITLE
UI fonts aren't bundled in the repo

### ISSUE THREAD

**Issue by jonpalmisc** [jonpalmisc/Maui#8]
The UI currently uses the Ubuntu and Ubuntu Mono fonts, but these aren't present on everyone's systems — they should be included with the build.

**Comment by xusheng6** [comment]
I see some fonts are already checked in: https://github.com/jonpalmisc/Maui/tree/master/ui/fonts. Should this be closed?

**Comment by jonpalmisc** [comment]
Yup, good catch—looks like I forgot about this issue after I added the fonts.
